apiVersion: v1
kind: Service
metadata:
  labels:
    app: model-evaluation
  name: model-evaluation-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: model-evaluation
