apiVersion: v1
kind: Service
metadata:
  labels:
    app: data-preparation
  name: data-preparation-svc
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: data-preparation
